# Generated by Django 3.2.5 on 2021-09-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('designation', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
    ]
